num1 = int(input("digite o primeiro numero:"))
num2 = int(input("digite o segundo numero:"))
num3 = int(input("digite o terceiro numero:"))
maior = max(num1 , num2 ,num3)
menor = min(num1 , num2 , num3)
print("O maior numero é:",maior)
print("O menor numero é:", menor)